# Generated by Django 5.1 on 2024-09-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_paymentlink_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="email",
            field=models.EmailField(
                default="default-email@gmail.com", max_length=100, unique=True
            ),
            preserve_default=False,
        ),
    ]
