# Generated by Django 5.1.1 on 2024-09-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_personalinfo_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentlink",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
