# Generated by Django 5.1.1 on 2024-09-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_paymentlink_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreenshotPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Path to store screenshots", max_length=255
                    ),
                ),
            ],
        ),
    ]
