# Generated by Django 5.1.1 on 2024-09-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_screenshotpath"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="expiry_date",
            field=models.CharField(max_length=5),
        ),
    ]
