# Generated by Django 5.1.1 on 2024-09-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_alter_paymentmethod_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentlink",
            name="website",
            field=models.CharField(
                choices=[("rakbank", "RakBank"), ("other", "Other")],
                default="rakbank",
                max_length=100,
            ),
        ),
    ]
