# Generated by Django 5.1.1 on 2024-09-18 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0008_csvfilepath"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentlink",
            name="payment_method",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_links",
                to="payment.paymentmethod",
            ),
            preserve_default=False,
        ),
    ]
