# Generated by Django 5.1.1 on 2024-09-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0009_paymentlink_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="code",
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
